# Generated by Django 2.0.5 on 2019-06-06 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationOfDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('recieved_date', models.DateTimeField(auto_now_add=True)),
                ('doctorSenderId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_doctor_notification', to='patient.user')),
                ('patientRecipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_doctor_notification', to='patient.user')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationOfHospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('recieved_date', models.DateTimeField(auto_now_add=True)),
                ('LabSenderId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_hospital_notification', to='patient.user')),
                ('patientRecipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_hospital_notification', to='patient.user')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationOfLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('recieved_date', models.DateTimeField(auto_now_add=True)),
                ('LabSenderId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_lab_notification', to='patient.user')),
                ('patientRecipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_lab_notification', to='patient.user')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationOfPharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('recieved_date', models.DateTimeField(auto_now_add=True)),
                ('patientRecipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_parmacy_notification', to='patient.user')),
                ('pharmacySenderId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_pharmacy_notification', to='patient.user')),
            ],
        ),
    ]
