# Generated by Django 2.0.5 on 2019-04-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Blood_type',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Chronic_diseases',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Disability_status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='Child_num',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.CharField(max_length=20),
        ),
    ]
