# Generated by Django 2.0.5 on 2019-04-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20190411_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Child_num',
            field=models.IntegerField(),
        ),
    ]
