# Generated by Django 2.0.5 on 2019-06-11 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_rate_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='Doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_rate', to='patient.user'),
        ),
    ]
