# Generated by Django 2.0.5 on 2019-06-07 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_notificationofdoctor_notificationofhospital_notificationoflab_notificationofpharmacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationofhospital',
            name='LabSenderId',
        ),
        migrations.RemoveField(
            model_name='notificationofhospital',
            name='patientRecipient',
        ),
        migrations.AlterField(
            model_name='notificationoflab',
            name='LabSenderId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_lab_notification', to='hospital.organization'),
        ),
        migrations.AlterField(
            model_name='notificationofpharmacy',
            name='pharmacySenderId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_pharmacy_notification', to='hospital.organization'),
        ),
        migrations.DeleteModel(
            name='NotificationOfHospital',
        ),
    ]
