# Generated by Django 2.0.5 on 2019-06-08 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20190522_0952'),
        ('patient', '0003_auto_20190607_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('recieved_date', models.DateTimeField(auto_now_add=True)),
                ('LabSenderId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_lab_notification', to='hospital.organization')),
                ('doctorSenderId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_doctor_notification', to='patient.user')),
                ('patientRecipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_recipient', to='patient.user')),
                ('pharmacySenderId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_pharmacy_notification', to='hospital.organization')),
            ],
        ),
        migrations.RemoveField(
            model_name='notificationofdoctor',
            name='doctorSenderId',
        ),
        migrations.RemoveField(
            model_name='notificationofdoctor',
            name='patientRecipient',
        ),
        migrations.RemoveField(
            model_name='notificationoflab',
            name='LabSenderId',
        ),
        migrations.RemoveField(
            model_name='notificationoflab',
            name='patientRecipient',
        ),
        migrations.RemoveField(
            model_name='notificationofpharmacy',
            name='patientRecipient',
        ),
        migrations.RemoveField(
            model_name='notificationofpharmacy',
            name='pharmacySenderId',
        ),
        migrations.DeleteModel(
            name='NotificationOfDoctor',
        ),
        migrations.DeleteModel(
            name='NotificationOfLab',
        ),
        migrations.DeleteModel(
            name='NotificationOfPharmacy',
        ),
    ]
