# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('temp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_1.admin')),
            ],
        ),
        migrations.CreateModel(
            name='temp_register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Patient_id',
            new_name='Patient',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='New_Password',
        ),
        migrations.AlterField(
            model_name='patient',
            name='Blood_type',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='patient',
            name='QR_code',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='Profile_picture',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='SSN_Picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
