# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-06 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0002_auto_20190306_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Submit_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
