# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-23 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0003_auto_20190222_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Password',
        ),
        migrations.AddField(
            model_name='user',
            name='Confirm_Pass',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='New_Password',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
