# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-06 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0003_auto_20190306_1324'),
        ('App_1', '0002_auto_20190305_1312'),
    ]

    operations = [
    ]
