# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0004_auto_20190302_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blocked_hospitals',
            old_name='hospital_id',
            new_name='hospital',
        ),
        migrations.RenameField(
            model_name='blocked_hospitals',
            old_name='manager_id',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='blocked_organizations',
            old_name='manager_id',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='blocked_organizations',
            old_name='organ_id',
            new_name='organ',
        ),
        migrations.RenameField(
            model_name='blocked_users',
            old_name='manager_id',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='blocked_users',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Doc_id',
            new_name='Doc',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='clinic_id',
            new_name='clinic',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='hospital_id',
            new_name='hospital',
        ),
        migrations.RenameField(
            model_name='multi_analytics',
            old_name='P_A_id',
            new_name='P_A',
        ),
        migrations.RenameField(
            model_name='multi_analytics',
            old_name='report_id',
            new_name='report',
        ),
        migrations.RenameField(
            model_name='multi_chronic',
            old_name='P_C_id',
            new_name='P_C',
        ),
        migrations.RenameField(
            model_name='multi_chronic',
            old_name='report_id',
            new_name='report',
        ),
        migrations.RenameField(
            model_name='multi_medecines',
            old_name='P_M_id',
            new_name='P_M',
        ),
        migrations.RenameField(
            model_name='multi_medecines',
            old_name='report_id',
            new_name='report',
        ),
        migrations.RenameField(
            model_name='multi_rays',
            old_name='P_R_id',
            new_name='P_R',
        ),
        migrations.RenameField(
            model_name='multi_rays',
            old_name='report_id',
            new_name='report',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='hospital_id',
            new_name='hospital',
        ),
        migrations.RenameField(
            model_name='patient_analytics',
            old_name='analy_id',
            new_name='analy',
        ),
        migrations.RenameField(
            model_name='patient_analytics',
            old_name='lab_id',
            new_name='lab',
        ),
        migrations.RenameField(
            model_name='patient_analytics',
            old_name='pat_id',
            new_name='pat',
        ),
        migrations.RenameField(
            model_name='patient_chronic',
            old_name='chr_id',
            new_name='chr',
        ),
        migrations.RenameField(
            model_name='patient_chronic',
            old_name='pat_id',
            new_name='pat',
        ),
        migrations.RenameField(
            model_name='patient_medicine',
            old_name='med_id',
            new_name='med',
        ),
        migrations.RenameField(
            model_name='patient_medicine',
            old_name='pat_id',
            new_name='pat',
        ),
        migrations.RenameField(
            model_name='patient_medicine',
            old_name='pharmacy_id',
            new_name='pharmacy',
        ),
        migrations.RenameField(
            model_name='patient_rays',
            old_name='lab_id',
            new_name='lab',
        ),
        migrations.RenameField(
            model_name='patient_rays',
            old_name='pat_id',
            new_name='pat',
        ),
        migrations.RenameField(
            model_name='patient_rays',
            old_name='ray_id',
            new_name='ray',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='prescription_id',
            new_name='prescription',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='report_id',
            new_name='report',
        ),
    ]
