# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-23 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0004_auto_20190223_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Confirm_Pass',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='New_Password',
            field=models.CharField(max_length=100),
        ),
    ]
