# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-23 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0005_auto_20190223_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Confirm_Pass',
            new_name='SSN_Picture',
        ),
    ]
