# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-25 05:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0007_auto_20190223_2247'),
        ('App_1', '0007_auto_20190224_1756'),
    ]

    operations = [
    ]
