# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-25 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0009_auto_20190225_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Profile_picture',
            field=models.FileField(max_length=5000, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='SSN_Picture',
            field=models.FileField(max_length=5000, upload_to=''),
        ),
    ]
