# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-25 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0014_auto_20190225_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Blood_type',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='patient',
            name='QR_code',
            field=models.CharField(max_length=500),
        ),
    ]
