# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-25 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0017_auto_20190225_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Profile_picture',
            field=models.ImageField(upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='user',
            name='SSN_Picture',
            field=models.ImageField(upload_to='SSN'),
        ),
    ]
