# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-26 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0019_auto_20190225_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='QR_code',
            field=models.ImageField(upload_to='QRCodes/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Profile_picture',
            field=models.ImageField(upload_to='Profiles/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='SSN_Picture',
            field=models.ImageField(upload_to='SSNs/'),
        ),
    ]
