# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-26 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0020_auto_20190227_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='QR_code',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='Profile_picture',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='SSN_Picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
