# Generated by Django 2.0.5 on 2019-05-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
