# Generated by Django 2.0.5 on 2019-06-08 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_analytics',
            fields=[
                ('analytics_id', models.AutoField(primary_key=True, serialize=False)),
                ('analytics_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='all_chronic',
            fields=[
                ('chronic_id', models.AutoField(primary_key=True, serialize=False)),
                ('chronic_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='all_medicine',
            fields=[
                ('medicine_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='all_rays',
            fields=[
                ('ray_id', models.AutoField(primary_key=True, serialize=False)),
                ('ray_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Registration_num', models.CharField(max_length=50)),
                ('Specialization', models.CharField(max_length=100)),
                ('Registration_date', models.DateField()),
                ('licence', models.CharField(max_length=250)),
                ('Last_date_payment', models.DateField()),
                ('End_date', models.DateField()),
                ('Specialization_type', models.CharField(max_length=100)),
                ('University', models.CharField(max_length=100)),
                ('Work_place', models.CharField(max_length=100)),
                ('Sub_syndicate', models.CharField(max_length=500)),
                ('General_secretary', models.CharField(max_length=500)),
                ('Working_till', models.DateField()),
                ('Graduation_year', models.DateField()),
                ('doc_rate', models.IntegerField(blank=True, null=True)),
                ('Doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.user')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.organization')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='multi_analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='multi_chronic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='multi_medecines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='multi_rays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='patient_analytics',
            fields=[
                ('P_A_id', models.AutoField(primary_key=True, serialize=False)),
                ('analytics_result', models.TextField()),
                ('analy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.all_analytics')),
                ('lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.organization')),
                ('pat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='patient_chronic',
            fields=[
                ('P_C_id', models.AutoField(primary_key=True, serialize=False)),
                ('chr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.all_chronic')),
                ('pat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='patient_medicine',
            fields=[
                ('P_M_id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_potions', models.IntegerField()),
                ('number_of_pills', models.IntegerField()),
                ('med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.all_medicine')),
                ('pat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.organization')),
            ],
        ),
        migrations.CreateModel(
            name='patient_rays',
            fields=[
                ('P_R_id', models.AutoField(primary_key=True, serialize=False)),
                ('rays_result', models.TextField()),
                ('lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.organization')),
                ('pat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('ray', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.all_rays')),
            ],
        ),
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('Disease_name', models.CharField(max_length=100)),
                ('Disease_level', models.CharField(max_length=100)),
                ('Disease_disc', models.TextField()),
                ('Doctor_signature', models.CharField(max_length=500)),
                ('next_appointment', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('report', models.AutoField(primary_key=True, serialize=False)),
                ('Submit_date', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.organization')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.prescription')),
            ],
        ),
        migrations.AddField(
            model_name='multi_rays',
            name='P_R',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.patient_rays'),
        ),
        migrations.AddField(
            model_name='multi_rays',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.report'),
        ),
        migrations.AddField(
            model_name='multi_medecines',
            name='P_M',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.patient_medicine'),
        ),
        migrations.AddField(
            model_name='multi_medecines',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.report'),
        ),
        migrations.AddField(
            model_name='multi_chronic',
            name='P_C',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.patient_chronic'),
        ),
        migrations.AddField(
            model_name='multi_chronic',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.report'),
        ),
        migrations.AddField(
            model_name='multi_analytics',
            name='P_A',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.patient_analytics'),
        ),
        migrations.AddField(
            model_name='multi_analytics',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.report'),
        ),
    ]
