# Generated by Django 2.0.5 on 2019-04-08 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_medicine',
            name='medicine_submit',
        ),
        migrations.AlterField(
            model_name='patient_analytics',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.organization'),
        ),
        migrations.AlterField(
            model_name='patient_medicine',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.organization'),
        ),
        migrations.AlterField(
            model_name='patient_rays',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.organization'),
        ),
    ]
