# Generated by Django 2.0.5 on 2019-05-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Graduation_year',
            field=models.DateField(),
        ),
    ]
