# Generated by Django 2.0.5 on 2019-04-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_auto_20190410_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='next_appointment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
